# Generated by Django 2.1.3 on 2019-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='ConfirmPassword',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='Password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
