# Generated by Django 2.1.3 on 2019-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_auto_20190424_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='Phone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='Village',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
