# Generated by Django 2.1.3 on 2019-04-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0004_farmer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='Place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
