# Generated by Django 2.1.3 on 2019-05-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0008_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Use',
            field=models.TextField(),
        ),
    ]
