# Generated by Django 2.1.3 on 2019-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0009_auto_20190501_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
