# Generated by Django 2.1.3 on 2019-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0011_dealernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCenterNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCenterService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.TextField()),
            ],
        ),
    ]
