# Generated by Django 2.1.3 on 2019-05-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0013_order_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='Rent_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='Return_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
