# Generated by Django 2.1.3 on 2019-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0015_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='replay',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='replay_date',
            field=models.DateField(null=True),
        ),
    ]
