# Generated by Django 2.1.3 on 2019-05-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0016_auto_20190503_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('que_date', models.DateTimeField()),
                ('replay', models.TextField(null=True)),
                ('replay_date', models.DateTimeField(null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Product')),
            ],
        ),
    ]
