# Generated by Django 2.1.3 on 2019-05-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0017_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Dealer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ontology.Dealer'),
            preserve_default=False,
        ),
    ]
