# Generated by Django 2.1.3 on 2019-05-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0018_order_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealernotification',
            name='DealerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Dealer'),
        ),
    ]
