# Generated by Django 2.1.3 on 2019-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0020_auto_20190504_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='ConfirmPassword',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
