# Generated by Django 2.1.3 on 2019-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0021_auto_20190504_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
