# Generated by Django 2.1.3 on 2019-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0023_dealer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Delivery',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Delivery_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
