# Generated by Django 2.1.3 on 2019-05-30 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0025_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ontology.Subcategory'),
        ),
    ]
