# Generated by Django 2.1.3 on 2019-05-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0026_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='Photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
